-- ============================================================
--  MERCER · Stock de Alfombras — Esquema Supabase
--  Pegá TODO esto en:  Supabase → SQL Editor → New query → Run
-- ============================================================

create table if not exists alfombras (
  id             bigint generated by default as identity primary key,
  codigo         text not null,
  nombre         text not null,
  color          text,
  medidas        text,
  mes_compra     text,
  anio_compra    text,
  contenedor     text,
  stock          integer default 0,
  precio_compra  numeric default 0,
  moneda         text default 'USD',
  proveedor      text,
  observaciones  text,
  created_at     timestamptz default now()
);

-- Habilitar Row Level Security
alter table alfombras enable row level security;

-- Política pública (lectura/escritura con la anon key)
-- Nombre "pub" — mismo patrón que usás en tus otros proyectos
drop policy if exists "pub" on alfombras;
create policy "pub" on alfombras for all using (true) with check (true);


-- ============================================================
--  TABLA VENTAS
-- ============================================================
create table if not exists ventas (
  id              bigint generated by default as identity primary key,
  fecha           date,
  producto        text not null,
  modelo          text,
  color           text,
  medida          text,
  cantidad        integer default 0,
  precio_unitario numeric default 0,
  importe_total   numeric default 0,
  cliente         text,
  vendedora       text,
  observaciones   text,
  anulada         boolean default false,
  fecha_anulacion date,
  motivo_anulacion text,
  stock_reintegrado boolean default true,
  created_at      timestamptz default now()
);

-- Si la tabla "ventas" ya existía de antes, estas líneas agregan las columnas nuevas
-- de anulación sin borrar datos. Es seguro correrlas siempre.
alter table ventas add column if not exists anulada boolean default false;
alter table ventas add column if not exists fecha_anulacion date;
alter table ventas add column if not exists motivo_anulacion text;
alter table ventas add column if not exists stock_reintegrado boolean default true;

alter table ventas enable row level security;
drop policy if exists "pub" on ventas;
create policy "pub" on ventas for all using (true) with check (true);
