-- ============================================================
--  MERCER · Stock de Alfombras — Esquema Supabase
--  Pegá TODO esto en:  Supabase → SQL Editor → New query → Run
-- ============================================================

create table if not exists alfombras (
  id             bigint generated by default as identity primary key,
  codigo         text not null,
  nombre         text not null,
  color          text,
  medidas        text,
  mes_compra     text,
  anio_compra    text,
  contenedor     text,
  stock          integer default 0,
  precio_compra  numeric default 0,
  moneda         text default 'USD',
  proveedor      text,
  observaciones  text,
  created_at     timestamptz default now()
);

-- Habilitar Row Level Security
alter table alfombras enable row level security;

-- Política pública (lectura/escritura con la anon key)
-- Nombre "pub" — mismo patrón que usás en tus otros proyectos
drop policy if exists "pub" on alfombras;
create policy "pub" on alfombras for all using (true) with check (true);
